### ISSUE TITLE
Add support for gzip encoding

### ISSUE THREAD

**Issue by patrickkwang** [ranking-agent/strider#10]
Clients can request this with the header `Accept-Encoding: gzip` and servers can respond with the header `Content-Encoding: gzip`.

See https://fastapi.tiangolo.com/advanced/middleware/#gzipmiddleware.

**Comment by maximusunc** [comment]
This hasn't been implemented by any Translator services in 3 years and there are no plans to do so, so I don't think this is an issue anymore.
