### ISSUE TITLE
Not returning Automat KEGG info?

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#102]
I am trying to establish a connection between the gene GK and the chemical glycerol.  We have an edge:
(GK)-[increases degradation of]->(glycerol) in KEGG automat, but I can't seem to get it from strider.

If I give this query:
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "a": {
                    "category": "biolink:ChemicalSubstance"
                },
                "b": {
                    "category": "biolink:Gene",
                    "id": "UniProtKB:P32189"
                }
            },
            "edges": {
                "ab": {
                    "subject": "a",
                    "object": "b"
                }
            }
        }
    },
    "knowledge_graph": {
        "nodes": [],
        "edges": []
    },
    "results": []
}
```

I don't get any results.  But if I change gene ID to the NCBIGene identifier instead, I do get results.  It looks like nodenorm handles this id fine, so don't know why that would be.

However, if I use the NCBIGene, I get many chemicals, including gycerol, but the edge to glycerol is an interacts_with edge from hmdb automat. That's true, but I don't see the degrades edge from KEGG.

(Came about as a result of 3/1 mini hackathon)

**Comment by cbizon** [comment]
Note: now with this query as written above, I am getting some results.  However, I'm still not getting the KEGG result I expect.  Also, I am seeing this kind of thing in the results:
```
{'node_bindings': {'b': [{'id': 'UniProtKB:P32189',
       'category': 'biolink:Gene'},
      {'id': 'NCBIGENE:2710', 'category': 'biolink:Gene'}],
     'a': [{'id': 'MESH:D000517', 'category': 'biolink:ChemicalSubstance'}]},
    'edge_bindings': {'ab': [{'id': 'MESH:D000517-NCBIGENE:2710-SEMMED Gene API-SEMMED'}]}},
```
For the 'b' node, which is defined in the query graph with a particular id, we are binding to 2 KG nodes, which should be the same node becuase Uniprotkb:P32189 == NCBIGENE:2710.

As an uposhot ( I suspect ) the GammaViewer also gets confused and shows the gene as a missing node:
![image](https://user-images.githubusercontent.com/10744350/111669223-f48f5d80-87ec-11eb-8310-51362f226f69.png)

**Comment by cbizon** [comment]
Using NCBIGENE in the initial query doesn't produce the doubled node, and GammaViewer works slightly better, but I still am not getting the KEGG results.

**Comment by alongreyber** [comment]
We have been working on a fix for this. The underlying issue has been that we were not expanding the related_to predicate correctly (we were only expanding to forward predicates and not reverse predicates as well). The fix to that issue has opened a whole can of worms about planning performance that we are working through. I'll keep you updated!

**Comment by alongreyber** [comment]
@cbizon I have been working on this query and I believe I have this mostly working. Patrick is away right now but I hope to get [this PR](#119) merged in early next week. The only remaining issue is with using the UniProtKB identifier. Right now, automat_kegg does not have any preferred prefixes set in the KP registry. This means that we won't convert Uniprotkb:P32189 -> NCBIGene:2710 because we don't know that automat_kegg needs a NCBIGene identifier.

**Comment by cbizon** [comment]
Interesting - all of the automat KPs should use the same set of preferred prefixes.   Are you pulling that information from somewhere, or is it put in by hand somewhere?

**Comment by alongreyber** [comment]
I think that the preferred prefixes are set by hand when the KPs are registered. I'm not 100% sure on that but I can check with Patrick on Monday.

**Comment by patrickkwang** [comment]
We are inputting that manually for now, but I believe that TRAPI v1.1 should allow KPs to publish that information themselves in a standardized form.

**Comment by alongreyber** [comment]
This should be working on the current master branch which should be deployed in a couple days. Let me know if there are any issues.
