### ISSUE TITLE
504 on gene-namedthing

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#112]
This query from NCATS (https://github.com/NCATSTranslator/testing/issues/12):

```
{
"message": {
"query_graph": {
"nodes": {
"n0": {
"id": "HGNC:3236",
"category":"biolink:Gene"
},
"n1": {
"category": "biolink:NamedThing"
}
},
"edges": {
"e01": {
"subject": "n0",
"object": "n1"
}
}
}
}
}
```

Is causing a 504 error in strider

**Comment by patrickkwang** [comment]
We have been working on some performance improvements for queries with named things and related-to edges, on the planning end. However KP calls can still be slow and we don't like to enforce timeouts on them. Probably we should do a little profiling to see if there are particular KPs holding us up or something.
