### ISSUE TITLE
Possible Misparsing of Node IDs

### ISSUE THREAD

**Issue by MarkDWilliams** [ranking-agent/strider#113]
I got the following response from Aragorn, and it looks like many of the results are repeated and some of the node ids are unusual like "http://purl.obolibrary.org/obo/go/extensions/reacto.owl#REACTO_R-HSA-182923" which seems like it is a misparse or something.

https://ars.transltr.io/ars/api/messages/523a2a09-ef98-4ad6-8f92-437df43ac9c5

**Comment by cbizon** [comment]
This looks like it might be partially a CAM-KP issue.  @balhoff do you agree?

**Comment by balhoff** [comment]
Yes, this is an ID for which we don't have a prefix mapping. I made an issue: https://github.com/NCATS-Tangerine/cam-kp-api/issues/228

**Comment by patrickkwang** [comment]
Duplicate results should be fixed.
