### ISSUE TITLE
Respond to queries with biolink:Protein

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#124]
See discussion here: 
https://github.com/NCATSTranslator/testing/issues/38

biolink has Gene and Protein categories.  We treat these as the same thing.  (there are good reasons to do this and other good reasons not to, but right now we are).

But, we are calling the merged category Gene, so if somebody queries with Protein, we are not returning data that is relevant.  We should internally replace any biolink:Protein node with a biolink:Gene node and run that query through strider.

**Comment by patrickkwang** [comment]
[per offline discussion with @cbizon]

Instead, let's replace biolink:Protein with biolink:GeneOrGeneProduct, then we're strictly augmenting/generalizing the question and can work with KPs that use either or both biolink:Gene and biolink:Protein.
