### ISSUE TITLE
Single Node Questions should be valid

### ISSUE THREAD

**Issue by maximusunc** [ranking-agent/strider#138]
I would expect this curl to work, but it returns a server error:
`curl -X POST "http://robokop.renci.org:5781/query?log_level=ERROR" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"message\":{\"query_graph\":{\"nodes\":{\"n0\":{\"id\":\"MONDO:0005148\",\"category\":\"biolink:Disease\"}},\"edges\":{}}}}"`

**Comment by alongreyber** [comment]
We don't have any way of solving single node questions. We have to contact KPs which correspond to edges. We could do a conversion like this when we get a single node query graph:
```json
{
    "nodes": {
        "n0": {
            "id": "MONDO:0005148"
        }
    }
}
```
to
```json
{
    "nodes": {
        "n0": {
            "id": "MONDO:0005148"
        },
        "n1": {
            "category": "biolink:NamedThing"
        }
    },
    "edges" : {
        "n0n1" : {
            "subject" : "n0",
            "object" : "n1",
            "predicate" : "biolink:related_to"
        }
    }
}
```

but I think that would be better handled on the Robokop side rather than the Strider side.

**Comment by patrickkwang** [comment]
Let's not do that, I don't think that's the intent. For any query without edges, we could just return the query graph and empty results. Probably we should add a warning indicating why we didn't try to do anything.

**Comment by cbizon** [comment]
Not clear what the intention would be.  But, one intention would be to add properties to a node. Once we have an add property operation and places that implement it, this becomes a totally reasonable query.

Also, if the query doesn't have an id, but does have a category, then it's "return me everything of this type", just like any other fill.  This would certainly be useful in conjunction with the WHERE stuff going into TRAPI.

**Comment by maximusunc** [comment]
Duplicated in #287, but that issue has more concrete ideas for doing this.
