### ISSUE TITLE
Add health-check endpoint(s)

### ISSUE THREAD

**Issue by patrickkwang** [ranking-agent/strider#144]
A shared Translator availability-monitoring system will need to ask Strider for a health self-check of some sort. This may include internal resource usage, availability of dependency services, etc. Currently, some use the /query endpoint with its OpenAPI example request, but that is non-ideal because a) it likely requires more time/resources than necessary to check Strider's health, and b) it requires access to one or more KPs, but we probably ought to decouple their availability from that of Strider itself. One or more dedicated endpoints would be better, but we need to figure out exactly what we can and should report.

**Comment by maximusunc** [comment]
This is covered in kubernetes as we have a health probe that pings the /docs endpoint.
