### ISSUE TITLE
Handle messy kp-registry output

### ISSUE THREAD

**Issue by patrickkwang** [ranking-agent/strider#145]
For example, what if there is no "preferred_prefixes" key?

**Comment by cbizon** [comment]
Is that particular problem going to be helped by TRAPI 1.1?

**Comment by patrickkwang** [comment]
Yes, in the sense that TRAPI 1.1 should allow us to deprecate our KP registry entirely in favor of the SmartAPI registry and /meta_knowledge_graph endpoints.

**Comment by patrickkwang** [comment]
This may be alleviated at least somewhat by #186.
