### ISSUE TITLE
Throttle KP calls

### ISSUE THREAD

**Issue by patrickkwang** [ranking-agent/strider#149]
We _may_ have recently sent 16k requests to a single KP in a very short span. It was understandably disconcerted. Let's look into how we may throttle requests on a per-KP basis.

**Comment by cbizon** [comment]
Note that we are getting blocked at bte with 429 Client Error: Too Many Requests for url: https://api.bte.ncats.io/v1/query (1039 times)

**Comment by cbizon** [comment]
See also https://github.com/RENCI-AUTOMAT/Automat-server/issues/5
