### ISSUE TITLE
subset bte

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#152]
There are a couple of bte sub-sources that produce large numbers of edges, and these can be pretty messy.

For instance, if I look up BiologicalProcessOrActivity related to Glycerol in robokop, I get maybe 10 or 20 nodes. But BTE produces over 4000.  

Some of those might be interesting? But I doubt it.  My guess is that this is mostly the fault of semmed, which I would argue we don't want as a first pass source anyway because it is not well curated.

So can we call bte in a way that says "don't give me semmed results"?  Maybe text-miner too.  I like both of these sources as either "I couldn't find anything else, let me try this last ditch" or as overlay sources.

**Comment by cbizon** [comment]
BTE results for the query above: https://arax.ncats.io/?source=ARS&id=197faf1d-52f0-449d-ad30-ab892d1a03e3 (takes forever to load of course)

**Comment by patrickkwang** [comment]
One idea is for Strider to filter results by provenance before returning, or to provide such constraints to BTE.

**Comment by maximusunc** [comment]
Closing. BTE doesn't provide a way to allow/disallow specific sub-sources. We've also implemented some internal filtering to remove promiscuous nodes.
