### ISSUE TITLE
Missing results for CAM-KP and REF-KG

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#173]
This query returns no results in strider:
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "name": "Glycerol",
                    "id": "CHEBI:17754"
                },
                "n2": {"category": "biolink:MolecularActivity"}
                },
            "edges": {
                "e0": {
                    "subject": "n2",
                    "object": "n0",
                    "predicate":"biolink:related_to"
                }
            }
        }
    }
}
```

The same query produces results in CAM-KP and the SRI KG.  I suspect that this has to do with the preferred prefixes in both cases: Strider will be normalizing this to a PUBCHEM.COMPOUND, but apparently both of these sources prefer CHEBI.

**Comment by patrickkwang** [comment]
The prefixes have been updated. Please confirm that this works now.

**Comment by cbizon** [comment]
So we are now getting results back, but only from automats.  We are querying CAM-KP, and REF-KG, but no results in the graph have them listed as sources.

With the changes to the logs, which are mostly very nice, I don't think I can tell exactly the trapi that was sent to each source, or whether any results were returned from that source, so it's a little hard to go much further.  My testing notebook is here: https://github.com/ranking-agent/robogallery/blob/master/troubleshooting/Strider_173.ipynb

**Comment by alongreyber** [comment]
Putting this issue on hold until we can talk to cam-kp and ref-kg using TRAPI 1.1.

**Comment by mmersmann** [comment]
CAM KP is TRAPI 1.1 compliant and registered with SmartAPI. There are issues calling CAM that Jim Balhoff is investigating.

**Comment by cbizon** [comment]
ref-kg should also be speaking 1.1. now.  Can we move this off hold?

**Comment by mmersmann** [comment]
**Action:** @patrickkwang to look into ref-kp SmartAPI registration to find out why it's not in our registry.
**Action:** @patrickkwang to ping CAM-KP about 504 errors.

**Comment by patrickkwang** [comment]
CAM-KP provides 15 results for this now. Ref-KG is not queried due to the lack of a TRAPI-1.1 instance. I have no reason to believe that it would not work if it existed, so this issue will be closed for now.
