### ISSUE TITLE
Update to biolink model version 2.1

### ISSUE THREAD

**Issue by alongreyber** [ranking-agent/strider#200]
Biolink released [version 2.0.0](https://github.com/biolink/biolink-model/releases/tag/2.0.0).

There is a [migration guide](https://biolink.github.io/biolink-model/Migration_2.0_Guide.html).

**Due:** July 28

**Comment by cbizon** [comment]
See discussion of timing on #translatorarchitecture slack channel

**Comment by mmersmann** [comment]
Patrick has put in a patch this morning. Not currently enforcing canonical predicate direction, but this work is on the way.

**Comment by mmersmann** [comment]
Complete
