### ISSUE TITLE
Strider sending 1.0 messages to camp-kp

### ISSUE THREAD

**Issue by Sharma05** [ranking-agent/strider#202]
I submitted a json query to strider [notebook](https://github.com/ranking-agent/robogallery/blob/master/user_queries/notebooks/Hangover_to_Chemical.ipynb) for a hangover exercise (Lactate: CHEBI:24996/PUBCHEM.COMPOUND:91435 --> Chemical).

curl -X POST "https://cam-kp-api-dev.renci.org/query?limit=10" -H "accept: application/json" -H "Content-Type: application/json" -d "{"message":{"query_graph":{"nodes":{"n0":{"categories":["biolink:ChemicalSubstance"],"name":"Chemical Substance","ids":["CHEBI:24996"]},"n1":{"categories":["biolink:ChemicalSubstance"],"name":"Chemical Substance"}},"edges":{"e0":{"subject":"n0","object":"n1"}}}}}"

I get back results from all KPs except cam-kp. When I directly use the cam-kp API, I do get results:

I expect to get results as:

https://user-images.githubusercontent.com/8516476/120666583-b522f580-c45a-11eb-8e81-34257c47f0b9.png

The error generated: "Response Error contacting KP"

<img width="1075" alt="Screen Shot 2021-06-04 at 10 31 54 AM" src="https://user-images.githubusercontent.com/8516476/120817883-1660cc80-c520-11eb-8892-ea12959e0a1a.png">

**Comment by cbizon** [comment]
@Sharma05 can you see if this is still occurring?  The recent deployment may have solved it...

**Comment by Sharma05** [comment]
@cbizon This error was resolved.
