### ISSUE TITLE
Response Error contacting Node Normalizer

### ISSUE THREAD

**Issue by Sharma05** [ranking-agent/strider#208]
Posted below query to strider from [notebook](https://github.com/ranking-agent/robogallery/blob/master/user_queries/notebooks/Hangover_to_Chemical.ipynb)

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": [
                        "biolink:ChemicalSubstance"
                    ],
                    "name": "Chemical Substance",
                    "ids": [
                        "CHEBI:24996"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:ChemicalSubstance"
                    ],
                    "name": "Chemical Substance"
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}

```
Error generated:

<img width="1052" alt="Screen Shot 2021-06-11 at 12 48 32 PM" src="https://user-images.githubusercontent.com/8516476/121722349-55a89380-cab3-11eb-8bf7-499a2a988fdf.png">

**Comment by cbizon** [comment]
The node normalizer url has changed to https://nodenormalization-sri.renci.org/1.1/

**Comment by cbizon** [comment]
In general I am confused about how URLs should be constructed for TRAPI, and for services like automat or NN that include both trapi and non-trapi paths.
