### ISSUE TITLE
How to handle similar chemicals.

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#211]
In [this issue](https://github.com/ranking-agent/strider/issues/210) we are dealing with a situation where we are not getting results back, and part of the problem is that the input CHEBI a racemic mixture (with no structure), while much of the data is related to a non-chiral version of the two possible structures.  From fix-it slack:

---

There are 4 different "chemical things" at play here.
12:39
There are a right and left handed version of this molecule:
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A77590
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A77591
And there is a version that ignores chirality:
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:77585
It's this last, nonchiral version that seems to have most of the information attached to it, e.g. it's what's annotated in hmdb and so on.

ebi.ac.ukebi.ac.uk
armodafinil (CHEBI:77590)
Chemical Entities of Biological Interest (ChEBI) is a freely available dictionary of molecular entities focused on 'small' chemical compounds.

ebi.ac.ukebi.ac.uk
(S)-modafinil (CHEBI:77591)
Chemical Entities of Biological Interest (ChEBI) is a freely available dictionary of molecular entities focused on 'small' chemical compounds.

ebi.ac.ukebi.ac.uk
2-[(diphenylmethyl)sulfinyl]acetamide (CHEBI:77585)
Chemical Entities of Biological Interest (ChEBI) is a freely available dictionary of molecular entities focused on 'small' chemical compounds.

There is a 4th thing which is a racemic mixture of the left- and right- versions of the compound:
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:31859
and this is the one that was used in the query

ebi.ac.ukebi.ac.uk
modafinil (CHEBI:31859)
Chemical Entities of Biological Interest (ChEBI) is a freely available dictionary of molecular entities focused on 'small' chemical compounds.

---

So what should we do?  I think we should at least fuzzy up input chemicals using our chemical-normalization graph, and/or incorporate some has_part edges.  It's possible that some of this work would be superseded by program-wide entity conflation work to come.   Or, we could include has_part type edges in the chem-norm graph as well.

Really, I think we'll eventually need to apply fuzzyness every time we hit a chemical, and we'll need to do it in strider rather than at query-ingest time.

**Comment by maximusunc** [comment]
@cbizon is this handled by drug-chemical conflation in NN now?

**Comment by cbizon** [comment]
Mostly, not completely.  In this case, it will help a lot b/c 31859 and 77585 are now conflated together.  But not the other two.

That said, I think that this is not primarily a strider issue, and should be handled elsewhere.
