### ISSUE TITLE
Production Strider Vs. Staging Strider

### ISSUE THREAD

**Issue by Sharma05** [ranking-agent/strider#213]
Why is the production strider url throwing errors whereas the staging url generates results?

Query:

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": [
                        "biolink:ChemicalSubstance"
                    ],
                    "name": "Chemical Substance",
                    "ids": [
                        "CHEBI:24996"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:ChemicalSubstance"
                    ],
                    "name": "Chemical Substance"
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}

```

**Comment by cbizon** [comment]
@Sharma05 can you give more details?  What re the errors you are getting on prod?

**Comment by Sharma05** [comment]
I will post more to this issue as I am running into bit weird issues/confusion now. Earlier, there was no result generated through the production url and now I am getting this error: 

<img width="1175" alt="Screen Shot 2021-06-17 at 1 53 02 PM" src="https://user-images.githubusercontent.com/8516476/122448972-56d63680-cf73-11eb-8671-0df69cb6bb68.png">


The error is similar to earlier issues on "connection aborted".

**Comment by Sharma05** [comment]
@cbizon so now for the staging url - if I remove the `?log_level=DEBUG` from `http://robokop.renci.org:5781/query?log_level=DEBUG` the query takes forever to run and if I add the `query['log_level'] = 'DEBUG'` to the the above query generates an error ```
"<function strider at 0x7fdf34990560> error: 500
{'message': {}, 'logs': [{'message': "Exception in Strider: TypeError('Object of type Request is not JSON serializable')"
```

but if I simply use `http://robokop.renci.org:5781/query?log_level=DEBUG` - I get back results

**Comment by cbizon** [comment]
For prod, it would be better to see the top of that error message where I think it will print out the HTTP error code if there is one.  I think you're getting a 502 (or at least I am).  Looking into it now...

**Comment by Sharma05** [comment]
Yes, it was 502 error. 
Interestingly, again for production url = 'https://strider.renci.org/1.1/query' and the below query:

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": [
                        "biolink:ChemicalSubstance"
                    ],
                    "name": "Chemical Substance",
                    "ids": [
                        "CHEBI:24996"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:ChemicalSubstance"
                    ],
                    "name": "Chemical Substance"
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    },
    "log_level": "DEBUG"
}
```

<img width="1149" alt="Screen Shot 2021-06-17 at 2 47 57 PM" src="https://user-images.githubusercontent.com/8516476/122456393-80935b80-cf7b-11eb-982f-6f99fd27d8b9.png">

and the Queried Sources:

<img width="1134" alt="Screen Shot 2021-06-17 at 2 51 55 PM" src="https://user-images.githubusercontent.com/8516476/122456439-9143d180-cf7b-11eb-98f2-3f4b9538f582.png">

@cbizon I am having a combination of all above errors every time I run the notebook, do you think it is a notebook compilation issue?

**Comment by cbizon** [comment]
I was just talking to Phil, and it seems like production strider is having some stability issues.  He just cycled it which is why the 502 went away.

So it looks like you're getting an error in the logs, instead of print(logmessage['message']) could you print(logmessage) ?

**Comment by Sharma05** [comment]
This is the first few lines of the print(logmessage):

<img width="1010" alt="Screen Shot 2021-06-17 at 4 13 36 PM" src="https://user-images.githubusercontent.com/8516476/122466661-973faf80-cf87-11eb-80d9-ccf8036c933e.png">

**Comment by cbizon** [comment]
Sorry, I should have been more explicit.  I meant to print the logmessage where level:ERROR.

Is it only that first one?  Because that's not very illuminating to me.

**Comment by Sharma05** [comment]
> Yes, it was 502 error.
> Interestingly, again for production url = 'https://strider.renci.org/1.1/query' and the below query:
> 
> ```
> {
>     "message": {
>         "query_graph": {
>             "nodes": {
>                 "n0": {
>                     "categories": [
>                         "biolink:ChemicalSubstance"
>                     ],
>                     "name": "Chemical Substance",
>                     "ids": [
>                         "CHEBI:24996"
>                     ]
>                 },
>                 "n1": {
>                     "categories": [
>                         "biolink:ChemicalSubstance"
>                     ],
>                     "name": "Chemical Substance"
>                 }
>             },
>             "edges": {
>                 "e0": {
>                     "subject": "n0",
>                     "object": "n1"
>                 }
>             }
>         }
>     },
>     "log_level": "DEBUG"
> }
> ```
> 
> <img alt="Screen Shot 2021-06-17 at 2 47 57 PM" width="1149" src="https://user-images.githubusercontent.com/8516476/122456393-80935b80-cf7b-11eb-982f-6f99fd27d8b9.png">
> 
> and the Queried Sources:
> 
> <img alt="Screen Shot 2021-06-17 at 2 51 55 PM" width="1134" src="https://user-images.githubusercontent.com/8516476/122456439-9143d180-cf7b-11eb-98f2-3f4b9538f582.png">
> 
> @cbizon I am having a combination of all above errors every time I run the notebook, do you think it is a notebook compilation issue?

@bizon attaching the same screenshot again...I did print the logmessage where level:ERROR. That is the only error. It is at the every bottom of the screenshot.

<img width="1127" alt="Screen Shot 2021-06-17 at 4 53 07 PM" src="https://user-images.githubusercontent.com/8516476/122470810-7fb6f580-cf8c-11eb-8440-c2f5cfb9b24a.png">
