### ISSUE TITLE
Strider Production URL returns no results and an error. 

### ISSUE THREAD

**Issue by Sharma05** [ranking-agent/strider#214]
Posted the query using url = 'https://strider.renci.org/1.1/query':

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": [
                        "biolink:ChemicalSubstance"
                    ],
                    "name": "Chemical Substance",
                    "ids": [
                        "CHEBI:24996"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:ChemicalSubstance"
                    ],
                    "name": "Chemical Substance"
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    },
    "log_level": "DEBUG"
}
```

The query returns no results.

<img width="1149" alt="Screen Shot 2021-06-17 at 2 47 57 PM" src="https://user-images.githubusercontent.com/8516476/122473387-c9eda600-cf8f-11eb-846c-737fb4e55574.png">

And an error:

<img width="755" alt="Screen Shot 2021-06-17 at 3 12 13 PM" src="https://user-images.githubusercontent.com/8516476/122473422-d4a83b00-cf8f-11eb-8d15-cff8ae15ef07.png">

NB: The staging URL does return results.

**Comment by Sharma05** [comment]
@cbizon should I consider this complete as Production URL is stable now?

**Comment by cbizon** [comment]
Yes, if the production strider is returning results

**Comment by patrickkwang** [comment]
Confirmed. This returns with results in production.
