### ISSUE TITLE
Strider returns "category" vs. "categories"

### ISSUE THREAD

**Issue by PhillipsOwen** [ranking-agent/strider#217]
Strider appears to be returning "category" in the result bindings. shouldn't this be "categories" now?

**Comment by patrickkwang** [comment]
That is a non-standardized field in results. We actually plan to remove it. Are you using it for something?

**Comment by PhillipsOwen** [comment]
i see these in the results, presumably from a call for node normalization.

      {
        "node_bindings": {
          "n0": [
            {
              "id": "MONDO:0005148",
              "category": [
                "biolink:Disease",
                "biolink:DiseaseOrPhenotypicFeature",
                "biolink:BiologicalEntity",
                "biolink:NamedThing"
              ]
            }
          ],
          "n1": [
            {
              "id": "HP:0012592",
              "category": [
                "biolink:DiseaseOrPhenotypicFeature",
                "biolink:PhenotypicFeature",
                "biolink:BiologicalEntity",
                "biolink:NamedThing"
              ]
            }
          ]
        },

**Comment by PhillipsOwen** [comment]
it could be coming in from node normalization. there is a new version of it coming out soon. i will close this and reopen if necessary.

**Comment by patrickkwang** [comment]
No, Strider definitely adds these fields. My counterpoint is, so what? This is compliant with TRAPI because extra properties are allowed on bindings.

**Comment by PhillipsOwen** [comment]
there is an endpoint in the node norm app that normalizes an entire trapi doc. i have changed the code in there to look for categories to account for the trapi 1.1.2 spec.

my presumption at the time was with the swap of which label is the alias would result in always seeing "categories". it will most likely fall over now if i dont check for either.

**Comment by patrickkwang** [comment]
In `message.query_graph.nodes[]` and in `message.knowledge_graph.nodes[]`, you should find "categories". Extra properties, including "category", are not allowed in the knowledge graph. In `message.results[].node_bindings.*[]`, where extra properties are allowed, Strider adds "category", and you can ignore it.
