### ISSUE TITLE
Aragorn not returning results for query

### ISSUE THREAD

**Issue by MarkDWilliams** [ranking-agent/strider#22]
I submitted the following query, but received `null` as the result.  Looking at it, it seems like a query that Aragorn would have results for, but let me know if there was some error with my query_graph.
https://ars.transltr.io/ars/api/messages/7a138d1a-fc1a-428b-b9c9-da43fbaaa30e
I also tried submitting directly to http://robokop.renci.org:5781/query rather than through the ARS but received the same response
```
{"message":
{

  "query_graph": {
    "nodes": [
      {
        "id": "n0",
        "type": "disease",
        "curie":"DOID:13636"
      },
      {
        "id": "n1",
        "type": "gene",
        "set": false
      },
      {
        "id": "n2",
        "type": "chemical_substance",
        "set": false
      }
    ],
    "edges": [
      {
        "id": "e0",
        "source_id": "n0",
        "target_id": "n1"
      },
      {
        "id": "e1",
        "source_id": "n1",
        "target_id": "n2"
      }
    ]
  }
}}
```

**Comment by cbizon** [comment]
I've identified the problem as an error in Automat's Pharos pull and will correct soon.

**Comment by cbizon** [comment]
OK, Aragorn is now returning answers for this query, with the following change:

To get this to run, you will need to remove "set": false.   That was a robokop-specific extension, and interestingly strider is interpreting that as a node property named "set".  In TRAPI 1.0, the name will be "is_set", but strider is not implementing that quite yet.

Thanks for the ticket @MarkDWilliams , Let us know if it's working for you

**Comment by MarkDWilliams** [comment]
Looks like that cleared it up.  Thanks!
