### ISSUE TITLE
No results returned by Aragorn for Tyrosinemia type 1-Gene-Chemical

### ISSUE THREAD

**Issue by Sharma05** [ranking-agent/strider#226]
The query:
Disease (MONDO:0010161 Tyrosinemia type 1) - related to - Gene - related to Chemical Substance

```
`{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": [
                        "MONDO:0010161"
                    ],
                    "categories": [
                        "biolink:Disease"
                    ]
                },
                "n1": {
		             "categories":[
                         "biolink:Gene"
                        ]
                },
                "n2": {
                    
                    
                    "categories":[
                        "biolink:ChemicalSubstance"
                       ]
               }
                
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates":["biolink:related_to"]

                },
                "e1": {
                    "subject": "n2",
                    "object": "n1",
                    "predicates":["biolink:related_to"]

                },
                "e2": {
                    "subject": "n2",
                    "object": "n0",
                    "predicates":["biolink:related_to"]

                }
            }
        }
    }
}`
```

This issue is related to [issue](https://github.com/NCATSTranslator/testing/issues/87)

**Comment by cbizon** [comment]
Priya, can you check and see if we are able to return any results for the first hop?

**Comment by Sharma05** [comment]
@cbizon first hop query returns 13 results. 

<img width="631" alt="Screen Shot 2021-07-22 at 2 27 21 PM" src="https://user-images.githubusercontent.com/8516476/126690186-0b2ffea6-84c0-4693-abbf-4b2d6642e07f.png">

For the full query, I get a remote connection error or 500 error sometimes.

**Comment by cbizon** [comment]
The predicates in biolink are a hierarchy, with each subpredicate is_a superpredicate.   So causes is_a related_to.   related_to is the top level predicate, so it's the same as asking for any predicate.   It's like asking for "shape" and returning a "rectangle".  That's ok, because a rectangle is a shape.

**Comment by patrickkwang** [comment]
Works in production.
