### ISSUE TITLE
No results: Imatinib--[correlated_with] -- Disease.

### ISSUE THREAD

**Issue by Sharma05** [ranking-agent/strider#227]
Query on:
imatinib--[correlated_with] -- Disease.

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids":["PUBCHEM.COMPOUND:5291"],
                    "categories":[
                        "biolink:ChemicalSubstance"
                       ]
                },
                "n1": {
                    "categories":[
                        "biolink:DiseaseOrPhenotypicFeature"
                       ]
               }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates":["biolink:correlated_with"]
                }
            }
        }
    }
}
```

Aragorn did not return results. An issue around COHD TRAPI was reported: COHD was invalid TRAPI.

Complete description of the query and error is [here](https://github.com/NCATSTranslator/testing/issues/88)

**Comment by cbizon** [comment]
Can you check whether the query runs in strider?

**Comment by Sharma05** [comment]
@cbizon. I ran the above query assuming there were changes to url's we have been using. The query runs and we get back 954 results.  The source is https://cohd.io/api//query. There were no log error generated. All the predicates are correlated_with. One of the first result is imatinib being correlated with Here, I am assuming nothing has Chronic myeloid leukemia in remission. I recall that that was one of the top results discussed during translator calls. 

I also checked in Robokop KG via neo4j and it doesn't have Imatinib (PUBCHEM.COMPOUND:5291). I also checked for other relevant identifiers through node normalizer and  rechecked  ROBOKOPKG  with id: CHEBI:45783 --- no results.

**Comment by Sharma05** [comment]
@cbizon related to above query using aragorn. 

<img width="1116" alt="Screen Shot 2021-07-22 at 1 09 15 PM" src="https://user-images.githubusercontent.com/8516476/126680505-2d9e99e2-1e40-40f8-a086-4a074a12bfde.png">


1432 results, source is again  https://cohd.io/api//query. I weird observation, I see an extra node which appears when I do gamma view. Probably you can explain that I don't know what is going behind aragorn. 

shouldn't the query be?:

<img width="1095" alt="Screen Shot 2021-07-22 at 1 15 23 PM" src="https://user-images.githubusercontent.com/8516476/126680859-60b86af0-2ecd-4a0b-b351-fcc892d45c53.png">

**Comment by cbizon** [comment]
So it sounds like we are now getting ARAGORN results, right?

If so, then let's close this issue.

If this is related to a standup, please make a note on the standup issue that ARAGORN is now returning results.

To answer your question above: one of the things that aragorn tries to do is group together answers. So if you ask something like A--(?) and you get back A--B and A--C then aragorn will look around and see if there is something else that B and C have in common.  Then it will return an answer (for instance) that looks like

```
A--B--D
   \      /
      C
```
Where D is the thing that B and C have in common.  It then updates the qgraph to have a place to bind D to.

**Comment by Sharma05** [comment]
Sure, will close this and post the note on the standup issue.

Okay, that's why. I thought we will always need to connect the nodes through specifying them. Interesting. 

Completed
