### ISSUE TITLE
Don't trust names from KPs

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#228]
We are calling ICEES DILI and it produced odd names for things.  i.e. it transforms our input node from a name of 

```
"n0": {
      ...
      "name": "drug-induced liver injury"
    },
```

into `"name":"DILIDx"`.

We should trust the names from the node normalizer (since we're calling that anyway)

**Comment by maximusunc** [comment]
OBE? ICEES DILI is no longer a KP, and was weird to be in Translator anyways. I don't think we normalize the received node names still, but it doesn't seem to be an issue anymore. Please reopen if it is.
