### ISSUE TITLE
Strider not talking to icees/asthma ?

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#229]
This query:
```
{
  "edges": {
    "e01": {
      "object": "n1",
      "predicates": [
        "biolink:correlated_with"
      ],
      "subject": "n0"
    }
  },
  "nodes": {
    "n0": {
      "categories": [
        "biolink:Disease"
      ],
      "ids": [
        "MONDO:0004979"
      ],
      "is_set": False
    },
    "n1": {
      "categories": [
        "biolink:ChemicalSubstance"
      ],
      "is_set": False
    }
  }
}
```

Returns almost 200 results in ICEES/asthma.

I believe that this is actually an ICEES issue, logged here: https://github.com/NCATS-Tangerine/icees-api/issues/125

but keeping here to track.

**Comment by patrickkwang** [comment]
At the moment, this query runs successfully in Strider but fails to return ICEES results because ICEES takes longer than 60 seconds and we cut it off.

**Comment by patrickkwang** [comment]
This works now, perhaps since ICEES has cached some of it.
