### ISSUE TITLE
Strider unable to process query due to constraints for Workflow A Advanced

### ISSUE THREAD

**Issue by Sharma05** [ranking-agent/strider#233]
Query: [here](https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowA/EGFR_advanced.json)

<img width="1098" alt="Screen Shot 2021-07-22 at 3 53 45 PM" src="https://user-images.githubusercontent.com/8516476/126701738-64005e34-e68d-417f-9670-78615a7e9c3c.png">

I think the strider is unhappy with constraints attribute.

**Comment by cbizon** [comment]
Should this be some 400 level error instead?

**Comment by Sharma05** [comment]
That is what I thought so too but even after using the json file as it is, I am still running into this error and the error is 500 (internal sever error). Will keep trying.

**Comment by Sharma05** [comment]
Let me know incase you test and do not get any errors.. Thanks

**Comment by mmersmann** [comment]
**Decision:** Constraint handling should be Strider's purview. Patrick may make constraint applicator a separate library.

**Comment by patrickkwang** [comment]
Strider completes this query now, although there are 0 results.
