### ISSUE TITLE
Sending incorrect queries (D.1)

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#243]
Workflow query D.1 is (named disease)-(thing)-(named disease)
```
{
    "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "object": "n01",
          "subject": "n00"
        },
        "e01": {
          "object": "n02",
          "subject": "n01"
        }
      },
      "nodes": {
        "n00": {
          "categories": [
            "biolink:Disease"
          ],
          "ids": [
            "DOID:14330"
          ]
        },
        "n01": {
          "categories": [
            "biolink:NamedThing"
          ]
        },
        "n02": {
          "categories": [
            "biolink:Disease"
          ],
          "ids": [
            "DOID:8778"
          ]
        }
      }
    }
  }
}
```

Somehow this is causing the following query (and queries like it) to be sent to various automats:
```
{"message": {"query_graph": {
"nodes": {
"n1": {"ids": ["NCBIGene:1956", "HGNC:3236"], "categories": ["biolink:Gene"], "is_set": false}, 
"n0": {"ids": ["RXNORM:1541732"], "categories": ["biolink:ChemicalSubstance"], "is_set": false}},
 "edges": {
"N1": {"subject": "n1", "object": "n0", "predicates": ["biolink:has_normalized_google_distance_with"], "relation": "N1"}}}}}
```

This is somehow a gene/chemical edge even though there is no such edge in the query.

Also, the predicate is specified to something quite strange, and which is also not in the query.

Also I don't know why "relation" is specified.

**Comment by patrickkwang** [comment]
This is wild. The qgraph is changed entirely from the original; it shares none of the same qnode/qedge keys. My best bet is that a KP monkeyed with the qgraph before returning it to us? And we completely failed to sanitize the response. I would imagine that this is prohibited by our traversal plan... The only place I've seen this normalized_google_distance thing before is RTX, so maybe they provided the first hop?

I'll look into it.

**Comment by cbizon** [comment]
Yeah, extremely bananas - thanks

**Comment by patrickkwang** [comment]
This completes in production. The results look reasonable. It is possible that this weirdness has been solved in the shuffle. Please re-open if we notice it again.
