### ISSUE TITLE
Add Liveness Probe to Strider

### ISSUE THREAD

**Issue by mmersmann** [ranking-agent/strider#247]
**Issue:** When a pod is moved or restarted, it doesn’t always come back with the data it needs.

**Solution:** Add a liveness probe to Strider.

**Comment by YaphetKG** [comment]
We have the helm chart configured to do liveliness probe on the deployment specs. The probe sends out post request using the example query provided on strider's query endpoint. the query is configured to timeout in 10 seconds and if it fails more than 5 times strider pod is restarted.
For KP registry we have probe setup to send GET requests to '/kps' endpoint similarly failures above 5 will trigger a restart .

Aside from this we have a cron job pod that runs every minute to refresh kp, this will ensure that we don't have to manually make post request to refresh the kps.

All of these options are configurable if we need to change them.

**Comment by patrickkwang** [comment]
@YaphetKG is this done?

**Comment by YaphetKG** [comment]
@patrickkwang , yes
