### ISSUE TITLE
Workflow B

### ISSUE THREAD

**Issue by karafecho** [ranking-agent/strider#248]
This issue is to kindly request that Ranking Agent tests [Workflow B](https://github.com/NCATSTranslator/minihackathons/tree/main/2021-12_demo/workflowB). Here is an example [TRAPI query](https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowB/B.1c_DILI_three-hop-from-disease-or-phenotypic-feature_trapi.json) that runs went sent through the ARS, but the only ARA that returns responses is ARAX. The ARS issue is apparently related to time-out errors that will be resolved with the release of TRAPI 1.2 and support for asynchronous queries, but that will not happen until early September. Thus, Hao and I would like to test direct ARA queries, and we are requesting your help. Note that we are also testing direct ARA queries using multihop.py, but strider tests would be helpful, as multihop.py doesn't support sophisticated features like ranking, etc.

The README file provides an overview of the workflow, including suggested input CURIES. Note that the first predicate will be changed from biolink:correlated_with to biolink:has_real_world_evidence_of_association_with, but I will be sure to alert you to this change after clinical KPs implement the new predicate. 

We are also testing query constraints, such as replacing biolink:related_to with biolink:interacts_with and biolink:Gene with biolink:BiologicalProcessOrPathway. Other options are welcome. For instance, if the full three-hop query does not run, or perhaps even if it does, Chris and I discussed testing the first two-hops using the answer coalescer.

We realize that you all are extremely busy, but we would greatly appreciate a few quick tests. Please feel free to reach out to me or Hao with questions.

**Comment by patrickkwang** [comment]
- [ ] **B.0:** 25728 results in <5 minutes 
- [ ] **B.1a:**
- [ ] **B.1b:**
- [ ] **B.1c:**
- [ ] **B.1d:**
- [ ] **B.1e:**
- [ ] **B.1f:**
- [ ] **B.2:**
- [ ] **B.3:**
- [ ] **B.4:**

**Comment by cbizon** [comment]
Nice. Heads up that a bunch of these workflows have just changed in the repo.

**Comment by CaseyTa** [comment]
Aragorn is currently not returning results for the B.1x and B.2x async queries. 

For example, [B.1a](https://arax.ncats.io/?source=ARS&id=e8acd249-0317-4384-8374-5ec17c17bfb6) is showing errors in the log of its response:
```
  "logs": [
    {
      "code": null,
      "level": "ERROR",
      "message": "strider error: HTML error status code 500 returned.",
      "time stamp": "09/23/2021-07:33:48",
      "timestamp": null
    },
    {
      "code": null,
      "level": "ERROR",
      "message": "answer_coalesce error: HTML error status code 500 returned.",
      "time stamp": "09/23/2021-07:33:48",
      "timestamp": null
    },
    {
      "code": null,
      "level": "ERROR",
      "message": "Exception: 'NoneType' object is not subscriptable",
      "time stamp": "09/23/2021-07:33:49",
      "timestamp": null
    },
    {
      "code": null,
      "level": "ERROR",
      "message": "omnicorp error: HTML error status code 500 returned.",
      "time stamp": "09/23/2021-07:33:49",
      "timestamp": null
    },
    {
      "code": null,
      "level": "ERROR",
      "message": "Exception: 'NoneType' object is not subscriptable",
      "time stamp": "09/23/2021-07:33:49",
      "timestamp": null
    },
    {
      "code": null,
      "level": "ERROR",
      "message": "weight error: HTML error status code 500 returned.",
      "time stamp": "09/23/2021-07:33:49",
      "timestamp": null
    },
    {
      "code": null,
      "level": "ERROR",
      "message": "Exception: 'NoneType' object is not subscriptable",
      "time stamp": "09/23/2021-07:33:49"
    },
    {
      "code": null,
      "level": "ERROR",
      "message": "score error: HTML error status code 500 returned.",
      "time stamp": "09/23/2021-07:33:49"
    }
  ],
```

And [B.2a](https://arax.ncats.io/?source=ARS&id=8c995a3f-1847-41a5-881b-e43777d74b4b) says `Query commenced. Will send result to https://ars-dev.transltr.io/ars/api/messages/a7e552dc-5b55-4a08-b6e4-b2f6c81cea89` (several hours after being run).

**Comment by karafecho** [comment]
@patrickkwang : B.1c and B.2c should return results from ICEES DILI. ARAX does, and the direct ARAGORN query below ran a few weeks ago.

**Comment by maximusunc** [comment]
@karafecho B.1c is returning results, and B.2c with biolink:treats predicate is returning results but none from ICEES DILI. The remaining workflows don't seem to be active anymore. Are there any other queries you want to test out?

**Comment by karafecho** [comment]
Thanks for following up on this, @maximusunc . I think Patrick's tracker is a bit outdated, however. The current Workflow B queries can be found [here](https://github.com/NCATSTranslator/minihackathons/tree/main/2021-12_demo/workflowB).

Thanks!

**Comment by karafecho** [comment]
That said, the B.1c results and B.2c results you report on are expected, so that is good.
