### ISSUE TITLE
Remove ChemicalSubstance Alias

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#271]
https://github.com/NCATSTranslator/minihackathons/issues/229

I think when we're sending SmallMolecule, we're also including ChemicalSubstance to try to smooth over the biolink 1-> 2 transition.

But now that everybody is on 2, at least one KP is complaining about the CS category, so I think we're ok to remove it?

**Comment by patrickkwang** [comment]
This may be unnecessary?

https://github.com/NCATSTranslator/testing/issues/115

Let's wait on feedback about expected behavior.
