### ISSUE TITLE
Discussion: Do we want a longer timeout for KPs

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#272]
We are missing results because of the 60 second timeout.   It's true for B queries and at least D.3.     What's the way out of this?   Tweak order of edges to reduce number of calls?   Increase the timeout and let the async query worry about how long it takes?  Take the hit on missing results?

**Comment by patrickkwang** [comment]
Imagine that we have 3-4 hops and Strider takes up to 60 seconds per hop, plus a little extra for merging, and the rest of ARAGORN takes as much time as Strider, we're pushing up against the 10-minute ARS limit, so 60 seconds seems reasonable for now. We should think about perhaps dynamically determining timeouts based on query size, etc. but maybe that's a longer-term issue.

**Comment by cbizon** [comment]
Agreed in principle, but with asyncquery the (5-minute) ARS limit doesn't matter as much?

**Comment by cbizon** [comment]
Perhaps the timeout could be dependent on whether this is a synchronous or asynchronous query?
