### ISSUE TITLE
self subclass edges as an edge in the query graph?

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#273]
https://github.com/NCATSTranslator/minihackathons/issues/233

This is a query that goes (chem1)-(protein1)-(protein2)-(chem2)

One answer is that protein1 = protein2 and the edge between them is a sublcass_of edge (A is always a subclass of itself).  So this is a valid answer, but is it one that we want to allow?

Maybe the self loops should be removed at the source (automat.ontology)?

**Comment by patrickkwang** [comment]
Another option is to somehow specify this in the query graph, e.g. "any predicate _except_ subclass_of".

**Comment by patrickkwang** [comment]
I don't think that Strider should disallow this sort of thing itself.
