### ISSUE TITLE
Add predicate hierarchy handling

### ISSUE THREAD

**Issue by patrickkwang** [ranking-agent/strider#29]

**Comment by alongreyber** [comment]
## Pseudocode

### Planning Step

1. Create list of *steps* - one per edge
1. For each step:
    - Get descendants of source node type
    - Get descendants of target node type
    - Permute descendants 
    - Add substep for each permutation
 
### Execution Step

1. For each step:
    - Ask KP for substep results
    - For each substep:
        - Rewrite source type to match Step type
        - Rewrite target type to match Step type

## Planned Changes

1. Use pydantic model for Step object
1. Use pydantic model for SubStep object
1. Rewrite planning step to include permutations of descendents
1. Rewrite execution to "recast" results to the type of the current step

**Comment by alongreyber** [comment]
Fixed in #31.
