### ISSUE TITLE
How to do live checks?

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#298]
We want to implement some live checks so that if our components go into space, we can notice it automatically and restart them.

Unfortunately the current version, which simply calls /docs, sometimes hangs when strider is busy working.   This leads to the effect of killing strider in the middle of jobs (not the intention!) 

This may be fixable with some uvicorn config or params for the probe, or some other approach.

**Comment by maximusunc** [comment]
This should now be covered by gunicorn. If a worker becomes unresponsive, it'll kill it and start a new one.
