### ISSUE TITLE
multiple deployments

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#314]
We need 2 deployments of KP.  One Prod and one Dev.  
- [ ] At runtime, there needs to be a config defining the environment
- [ ] Based on the config, use the correct versions of kp-registry and nodenormalizer.  Node norm should have a smartapi registration with the right x-maturity level, but kp registry won't
- [ ] Deploy

**Comment by richakanwar13** [comment]
Complete as of 12/3.
