### ISSUE TITLE
Find a way to help ensure documentation is in sync

### ISSUE THREAD

**Issue by alongreyber** [ranking-agent/strider#319]
After #203 is merged, we will have a good bit of documentation which will get out of date quickly. Here's an idea for how to keep it up to date:

1. Add hidden file references to the top of each documentation. So strider/query_planning would have something like this in the markdown:
```
<!-- REF: strider/query_planner.py -->
```

2. Write a CI script to comment on all PRs that modify `strider/query_planner.py` with a reminder to update documentation if necessary.

**Comment by alongreyber** [comment]
@davefol I can implement this, but I wanted your feedback first. Got any better ideas?

**Comment by davefol** [comment]
I like this. go for it.

**Comment by maximusunc** [comment]
Not going to implement this.
