### ISSUE TITLE
Update PLANNING_OVERVIEW.md

### ISSUE THREAD

**Issue by davefol** [ranking-agent/strider#321]
@uhbrar can you take a look at this and info dump anything you have? We may have to team this to get a nice description of query planning but I think its mildly important that we have a couple people who know whats going on with that code.

**Comment by uhbrar** [comment]
I don't have much info right now, but I should be able to get things figured out if I give it a good look. I think between Kenny and I, we should be able to get some helpful documentation written up.

**Comment by maximusunc** [comment]
Expanding to #462
