### ISSUE TITLE
Async Endpoint Failure Reporting

### ISSUE THREAD

**Issue by kennethmorton** [ranking-agent/strider#343]
Imagine a downstream service using the async endpoint, but strider fails (in some bad way). The downstream service, never gets a response from strider and strider will never report that it failed. We need to somehow catch some/more/all failures on the strider end and make sure we send some callback response. 

This is important to do and should be well handled translator wide. The downstream service in this case is Aragorn, but Aragorn (and every other ARA) also has this problem when the downstream service is the ARS.

**Comment by maximusunc** [comment]
Per the ARAGORN integration call on 12/10/21, this seems to be an issue in Aragorn and not Strider. While Strider is sending a response back, Aragorn is closing the connection when it receives any new queries on other workers. Regardless, we should still make sure we're properly handling any failure cases in our async queries.
