### ISSUE TITLE
Missing, variable results

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#361]
Query: (ValproicAcid)-(disease or phenotype)-(gene ALAS1)
```
query={
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "disease",
                    "object": "n00"
                },
                "e01": {
                    "subject": "disease",
                    "object": "n01"
                }
            },
            "nodes": {
                "n00": {
                    "ids": [
                        "PUBCHEM.COMPOUND:3121"
                    ]
                },
                "n01": {
                    "ids": [
                        "NCBIGene:211"
                    ]
                },
                "disease":{
                    "categories":["biolink:DiseaseOrPhenotypicFeature"]
                }
            }
        }
    },
    "log_level": "WARNING"
}
```

When this query is run against BTE or KGX, there are 30-40 answers.
From strider, I have seen anywhere between 4 and 20-some answers.   

1. If we are hitting both of these sources, why don't we have all their answers?
2. BTE is sometimes timing out at 60 seconds so that may be part of the issue.  Running it by hand it takes about 1:05 to return (sigh).
3. I am seeing this in the logs for strider:
```
{
        "message": "Received non-TRAPI compliant response from RTX KG2 (dev)",
        "error": "1 validation error for Response\nmessage -> results\n  unhashable type: 'list' (type=type_error)",
        "timestamp": "2022-03-13T18:28:54.848727",
        "level": "WARNING"
    },
```
 Why is strider talking to the dev version of KG2?  Also, if KG2 is returning invalid TRAPI, we should make an issue on their repo.
4. We are getting validation errors like this from basically everybody, which makes me wonder if there's a problem with the validation code.
```
{
        "message": "Received non-TRAPI compliant response from Biothings Explorer ReasonerStdAPI",
        "error": "2 validation errors for QueryGraph\nnodes\n  field required (type=value_error.missing)\nedges\n  field required (type=value_error.missing)",
        "timestamp": "2022-03-13T18:31:27.552455",
        "level": "WARNING"
    },
```

**Comment by maximusunc** [comment]
I've been unable to fully test this because KG2 is currently not a fully valid KP. I've opened an issue here: https://github.com/RTXteam/RTX/issues/1828

**Comment by maximusunc** [comment]
There's a bug in reasoner pydantic where we're incorrectly invalidating responses from KPs that have lists as extra attributes in the results. Here's the issue: https://github.com/TranslatorSRI/reasoner-pydantic/issues/35

**Comment by maximusunc** [comment]
KP Registry will try and fall back to the other maturity if one isn't available. I'm assuming KG2 prod was down and we ended up using dev.
