### ISSUE TITLE
Should we merge these?

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#370]
https://arax.ncats.io/?r=3a65ce0d-0ffb-43af-b228-6233d7fe428a

This is a 2 hop pinned on both ends.   There are 3 answers with the same middle node.  Should we merge them?  Two of them are the same except that one of the edges is flipped around.  (I assume those come from different sources though)

**Comment by kennethmorton** [comment]
I'm fairly sure that we will merge these after a Biolink model update. Until about 3mo ago there was an issue in the annotations area of the enables slot definition. It has since been fixed, but strider needs the upgrade.

**Comment by maximusunc** [comment]
@cbizon that PK is no longer valid. Are you able to reproduce? I'm leaning towards thinking this has already been fixed either in Biolink or in reasoner_pydantic.

**Comment by cbizon** [comment]
Probably true - I don't recall the particular query, so I think it's ok to close as unreproducible.
