### ISSUE TITLE
Implement edge merging post-Relay

### ISSUE THREAD

**Issue by capasfield** [ranking-agent/strider#384]
This issue stems from a discussion of “How do we fix subclass of?” during the [8/19 Aragorn Team Meeting](https://docs.google.com/document/d/1x_ukP9eyy8ahb6ZlZAg78bdf6H2XxkcfGKR_r3WRcuM/edit?pli=1)

https://github.com/ranking-agent/aragorn/issues/115

**Comment by maximusunc** [comment]
We do edge merging now.
