### ISSUE TITLE
Losing sentences

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#397]
There is a desire that when semmed edges are returned, that a sentence should also be returned.

When strider retrieves semmed edges from RTX-KG2 (and mabye BTE) they have sentences, but strider is removing them before sending back to aragorn.

See this notebook for an example: https://github.com/ranking-agent/robogallery/blob/master/tests/LosingSentences.ipynb

**Comment by maximusunc** [comment]
I just ran a query against current Strider and confirmed that sentences from semmed are being returned.
