### ISSUE TITLE
filter out steps that are too specific for source node

### ISSUE THREAD

**Issue by patrickkwang** [ranking-agent/strider#4]
e.g. we got a disease_or_phenotypic_feature and step requires disease

**Comment by cbizon** [comment]
Do you want to filter it out?  It might be right?  Could it just be maybe deprioritized?

**Comment by patrickkwang** [comment]
Sorry, I don't think my text above properly explains this. "Step" refers to a KP call. Imagine that, in the course of walking around the query graph, we receive an entity whose most specific type is just `disease_or_phenotypic_feature`. There is a KP advertising that it can make `disease`→`gene` links. Do we send our entity there? Not if everyone is normalizing their data in exactly the same way.

**Comment by patrickkwang** [comment]
#81
