### ISSUE TITLE
Double check molepro

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#407]
I ran a query in ci, creative mode treats for a rare disease "Brittle Cornea Syndrome 1".  I don't really expect much - many ara's including robokop return 0.  Strider returns tens of thousands.

It looks to me like at least part of the problem is that molepro is returning superclass answers.  So it is rebinding the input disease to superclasses of the disease.

Of the 251 results returned by the treats query directly to ci in molepro, they are all to superclasses:
MONDO:0000839 OBSOLETE TERM 4
MONDO:0002254 syndromic disease 2
MONDO:0020066 Ehlers-Danlos syndrome 2
MONDO:0003900 connective tissue disorder 12
MONDO:0005328 eye disorder 77
MONDO:0003847 Mendelian disease 1
MONDO:0005093 skin disorder 153

(the number at the end is the number of results)

None of these are valid.

This is obviously molepro's problem to fix, but we might need an interim solution where we filter some/all of these, b/c it 1) makes us return crap and 2) take forever.  Our top results are things like "X treats eye disease"

**Comment by cbizon** [comment]
https://github.com/broadinstitute/molecular-data-provider/issues/308

**Comment by maximusunc** [comment]
Issue has been fixed on molepro.
