### ISSUE TITLE
No AuxGraphs

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#411]
BTE is returning auxgraphs, but strider is not passing them along.

For a treats lookup query (MONDO:0018912) BTE is using auxiliary graphs to denote a subclass result.  So they have an edge with a support graph property. The name of the support graph ends up looking like support0-PUBCHEM.COMPOUND:44139752-treats-MONDO:0018912-via_subclass

When I run the inferred lookup query for that id through strider, I don't think that the auxiliary graph is ever being returned (though the support-graph attribute is in place).  That leads to some downstream dangling pointers.

**Comment by maximusunc** [comment]
Could you post the original query please?

**Comment by cbizon** [comment]
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "disease": {
                    "ids": [
                        "MONDO:0018912"
                    ]
                },
                "chemical": {
                    "categories": [
                        "biolink:ChemicalEntity"
                    ]
                }
            },
            "edges": {
                "t_edge": {
                    "object": "disease",
                    "subject": "chemical",
                    "predicates": [
                        "biolink:treats"
                    ]
                }
            }
        }
    }
}
```

**Comment by maximusunc** [comment]
Should be fixed in https://github.com/ranking-agent/strider/pull/413/commits/b3e3ba1f131741ca436596545a02f173e94a85ad

**Comment by maximusunc** [comment]
Confirmed on dev that auxiliary graphs are being returned!
