### ISSUE TITLE
Strider Not Conacting CHP

### ISSUE THREAD

**Issue by uhbrar** [ranking-agent/strider#455]
As shown in https://github.com/ranking-agent/aragorn/issues/266

CHP does have a metakg that shows this edge, which means it should be contacted. When removing the allowlist, the following query plan is generated:

`['infores:spoke', 'infores:service-provider-trapi', 'infores:rtx-kg2', 'infores:automat-monarchinitiative', 'infores:automat-robokop', 'infores:automat-hetionet']`

This indicates that strider is not correctly interpreting the metakg from CHP, or is unable to assign that edge to CHP. I haven't been able to verify whether or not CHP is actually in the KP registry because the `/kps` endpoint is currently returning a 500 error.

**Comment by maximusunc** [comment]
This has been fixed in dev and CI on CHP side. Their url/server in SmartAPI was causing some sort of redirect to get the actual meta_knowledge_graph, and that was causing the kp registry to skip it. They've fixed their redirect and CHP is being used again.
