### ISSUE TITLE
Move logging to separate library

### ISSUE THREAD

**Issue by alongreyber** [ranking-agent/strider#48]
It may be useful for other Translator projects to be able to use the Python logging structure and store the results in the TRAPI message. Our utilities would be helpful for setting that up.

**Comment by patrickkwang** [comment]
Yes, if this can be done neatly it could be very useful. There's the Redis db involved, so it sounds tricky to make this an easily-incorporated library.

**Comment by maximusunc** [comment]
Not going to implement.
