### ISSUE TITLE
KP Logs

### ISSUE THREAD

**Issue by alongreyber** [ranking-agent/strider#49]
Right now KPs respond with a TRAPI message, but we are ignoring the logs and only focusing on results. Should we be appending those logs to our logs? @patrickkwang.

**Comment by patrickkwang** [comment]
Not in full, for sure; in theory we get logs for every KP call. But when we encounter a KP error, we could try to pick out some kind of helpful message from the returned logs.

I haven't actually seen any logs coming from KPs yet, so this is low priority.

**Comment by maximusunc** [comment]
Not going to implement.
