### ISSUE TITLE
Aragorn Smart-API Registered Query Example Not Returning

### ISSUE THREAD

**Issue by MarkDWilliams** [ranking-agent/strider#54]
It seems like the example query included in the SmartAPI registration does not return results.  Can you let me know if this is user error on my part or if there is some issue with the server/registered information?
https://smart-api.info/ui/40432beee9e4945c5b824d9c3ac8b1b9#/query/sync_query_query_post

**Comment by patrickkwang** [comment]
Neither. This question simply does not have any answers given the currently attached assortment of KPs. We are still in the process of re-attaching KPs after the TRAPI 1.0 upgrade, so that may change.

**Comment by MarkDWilliams** [comment]
Ah, understood.  Closing the ticket
