### ISSUE TITLE
Query plan not contacting all available KPs

### ISSUE THREAD

**Issue by alongreyber** [ranking-agent/strider#62]
The following query graph is not contacting a KP that advertises AnatomicalEntity.
```json
{
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "category": "biolink:Gene"
        },
        "n1": {
          "category": "biolink:AnatomicalEntity",
          "id": "GO:0005634"
        }
      },
      "edges": {
        "e0": {
          "subject": "n0",
          "object": "n1",
          "predicate": "biolink:part_of"
        }
      }
    }
  }
}
```

**Comment by patrickkwang** [comment]
Correction: Strider is contacting the KP, but with `biolink:CellularComponent` rather than `biolink:AnatomicalEntity`. The KP advertises both, but only has data for the latter. I think Strider should ask for both.

**Comment by cbizon** [comment]
biolink:CellularComponent is_a biolink:AnatomicalEntity.   I think this is CAM KP, I would think it would be able to respond to either...

**Comment by patrickkwang** [comment]
My guess is that the relationship(s) we need are annotated at the AnatomicalEntity level, so we need to ask for that or superclasses. That's my understanding of how it works, anyway.

**Comment by cbizon** [comment]
Yeah, I agree.  But I'm confused about a couple things - one is 
> KP advertises both, but only has data for the latter. 
makes it sound like the data is not there for Anatomical Eneityt

The other is that this GO term should have CellularComponent as its leafiest class, so I would think Cellular Component would work

**Comment by patrickkwang** [comment]
If the query we _are_ sending to CAM is not working as expected, that's a different issue.
