### ISSUE TITLE
Contacting automat/goa but not getting results

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#66]
Message
```
{'message': {'query_graph': {'nodes': {'a': {'category': 'biolink:MolecularActivity',
     'id': 'GO:0002020'},
    'b': {'category': 'biolink:Gene'}},
   'edges': {'ab': {'subject': 'a',
     'object': 'b',
     'predicate': 'biolink:enabled_by'}}}}}
```

There is data for this in automat/human-goa, sending this query there directly produces many results.   Sending to strider gives no results.  In the logs it looks like human-goa is in the plan....

**Comment by alongreyber** [comment]
Looks like this is working now, let me know if you have any issues.
