### ISSUE TITLE
(chemical)-[affects_expression_of]->(gene) hangs

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#70]
```
{'message': {'query_graph': {'nodes': {'a': {'category': 'biolink:ChemicalSubstance', 'id': 'CHEBI:28119'}, 'b': {'category': 'biolink:Gene'}}, 'edges': {'ab': {'subject': 'a', 'object': 'b', 'predicate': 'biolink:affects_expression_of'}}}}}
```

Seems to run muuuuch longer than I would expect.  I gave up after 15 minutes or so; I think it actually ran much longer...

**Comment by patrickkwang** [comment]
This does take a long time. It seems to complete, though. Less than 15 minutes for me. It's big, most or all from automat/ctd.

**Comment by patrickkwang** [comment]
It's possible that other nasty things are happening here because there are so many results. For example, we may be DoS-ing the node normalizer?

**Comment by cbizon** [comment]
Could be - I think we should leave it open to investigate

**Comment by alongreyber** [comment]
This runs in about 30 seconds now and seems to produce good results. Let me know if there are any other issues with this query and we can reopen.
