### ISSUE TITLE
output of strider causing errors in answer coalesce.

### ISSUE THREAD

**Issue by PhillipsOwen** [ranking-agent/strider#71]
the output of a call to strider when fed into answer coalesce and reports formatting errors. this is due to lacking the "type" element in the "attributes".

here is how to setup the test.

the following was input to strider:
{
    "message": {
      "query_graph": {
        "nodes": {
          "n00": {
            "id": "MONDO:0005784",
            "category": "biolink:Disease"
          },
          "n01": {
            "category": "biolink:Disease"
          }
        },
        "edges": {
          "e00": {
            "subject": "n00",
            "object": "n01",
            "predicate": "biolink:subclass_of"
          }
        }
      }
    }
}

an example output of strider attributes:

          "attributes": [
            {
              "name": "equivalent_identifiers",
              "value": {
                "id": {
                  "label": "kidney disease",
                  "identifier": "MONDO:0005240"
                },
                "db_ids": {
                  "MONDO": [
                    "MONDO:0005240"
...

**Comment by cbizon** [comment]
@PhillipsOwen Is this still occuring?

**Comment by PhillipsOwen** [comment]
i just checked and it isnt. closing the ticket...
