### ISSUE TITLE
strider not synonymizing?

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#72]
Here's a query that doesnt work:
```
{"message": {
    "query_graph": {
        "nodes": {
            "n0": {
                "category": "biolink:ChemicalSubstance"
            },
            "n1": {
                "id": "UMLS:C0032961",
                "category":"biolink:PhenotypicFeature"
            }
        },
        "edges": {
            "e00": {
                "subject": "n0",
                "object": "n1",
                "predicate":"biolink:contraindicated_for"
                }
            }
        }
    }
}
```

But if I change UMLS:C003291 to NCIT:C92933, I get results...

According to nodenorm, these are the same thing (UMLS normalizes to NCIT)

**Comment by cbizon** [comment]
Here's another example: 
```
{
  "message": {
    "query_graph": {
      "edges": {
        "e01": {
          "object": "n0",
          "predicate": 
            "biolink:decreases_activity_of",
          "subject": "n1"
        }
      },
      "nodes": {
        "n0": {
          "id": "NCBIGene:6794"
        },
        "n1": {
          "category": "biolink:ChemicalSubstance"
        }
      }
    }
  }
 }
```
works, but fails if I change n0 to the equivalent HGNC:11389

**Comment by alongreyber** [comment]
The second query looks like it works, even with the HGNC:11389 identifier.

**Comment by cbizon** [comment]
I think what' going on here is that nodenorm doesn't guarantee that there is only one UMLS or NCIT identifier per concept.  Those vocabularies are pretty granular, and in this case we are merging at the level of MESH id, and it's pushing together 2 UMLS and 2 NCITs:

```
{
    "id": {
      "identifier": "NCIT:C25742",
      "label": "Pregnancy"
    },
    "equivalent_identifiers": [
      {
        "identifier": "NCIT:C25742",
        "label": "Pregnancy"
      },
      {
        "identifier": "NCIT:C92933",
        "label": "Normal Pregnancy"
      },
      {
        "identifier": "UMLS:C0032961",
        "label": "Pregnancy"
      },
      {
        "identifier": "UMLS:C0232989",
        "label": "Normal pregnancy"
      },
      {
        "identifier": "MEDDRA:10036556"
      },
      {
        "identifier": "SNOMEDCT:289908002"
      },
      {
        "identifier": "SNOMEDCT:72892002"
      },
      {
        "identifier": "MESH:D011247",
        "label": "Pregnancy"
      }
    ],
```

If I try these identifiers in automat/mychem, the one that has results is NCIT:C92933.  

Now, one could argue persuasively that automat should be using the canonical id, but it's perversely using the other NCIT identifier.  I see two options, probably both of which should be implemented:

1) automats should have their identifiers cleaned up. (@PhillipsOwen )
2) When picking identifiers to send to a service, recognize that if the preferred prefix is X, that there may be more than one identifier with that prefix, and send both of them, merging results.

**Comment by cbizon** [comment]
Hmm, on the gene/chemical query, I get no answers back for either version now.  @alongreyber it sounds like you were getting answers for that one?
