### ISSUE TITLE
Handle symmetric and inverse predicates

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#74]
```
corr={
        "message": {
            "query_graph": {
                "edges": {
                    "e00": {
                        "subject": "n00",
                        "object": "n01",
                        "predicate": "biolink:correlated_with"
                    }
                },
                "nodes": {
                    "n00": {
                        "id": "MONDO:0001627",
                        "category": "biolink:Disease"
                    },
                    "n01": {
                        "category": "biolink:ChemicalSubstance"
                    }
                }
            }
        }
    }
```

Returns no answers.  But if I swap subject and object on e00, I do get answers.  biolink:correlated_with is symmetric, so it should be found either way.

**Comment by alongreyber** [comment]
We haven't implemented symmetric predicates yet. @patrickkwang is this something I should work on?

**Comment by patrickkwang** [comment]
This should fit pretty well with our augmented query graph approach. Are we using the original qgraph or the augmented one to filter out results we receive from KPs? It needs to be the latter or we'll have problems here.

**Comment by alongreyber** [comment]
This has been fixed.
