### ISSUE TITLE
strider inputs usig correlated_with no longer return a knowledge graph or results in the response.

### ISSUE THREAD

**Issue by PhillipsOwen** [ranking-agent/strider#75]
this query used to return knowledge graph and results. it does no longer. seems to be following the use of correlated_with or positively_correlated_with. could possibly be a icees issue.

{
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "id": "MONDO:0004979",
          "category": "biolink:Disease"
        },
        "n1": {
          "category": "biolink:ChemicalSubstance"
        }
      },
      "edges": {
        "e01": {
          "subject": "n0",
          "object": "n1",
          "predicate": "biolink:correlated_with"
        }
      }
    }
  }
}

**Comment by patrickkwang** [comment]
Works as of #83.
