### ISSUE TITLE
Strider isn't returning correct http headers on some queries.

### ISSUE THREAD

**Issue by maximusunc** [ranking-agent/strider#87]
```
{
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "category": [
            "biolink:Disease"
          ],
          "id": [
            "MONDO:0005737"
          ],
          "name": "Ebola Hemorrhagic Fever"
        }
      },
      "edges": {}
    }
  }
}
```
throws a CORS error in Robokop.

**Comment by alongreyber** [comment]
I believe that this is an issue but I haven't been able to reproduce locally. Can you send me a list of steps you took?

**Comment by alongreyber** [comment]
Still haven't been able to reproduce. Let me know if you run across this issue again.

**Comment by maximusunc** [comment]
When I ask this question, I'm getting a 422 Error:
- Go to http://robokop.renci.org:7080/simple/question
- Select Blank
- Enter any question title
- Click Add Node
- Type in 'MONDO:0005737' (Name Resolver is currently down)
- Select the only option in the drop down
- Click Save
- Click Submit

Nothing is showing up in the DevTools Network tab, but the error message being shown is an Axios error after not being able to post to Strider.

**Comment by maximusunc** [comment]
I would expect this curl to work:
`curl -X POST "http://robokop.renci.org:5781/query?log_level=ERROR" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"message\":{\"query_graph\":{\"nodes\":{\"n0\":{\"id\":\"MONDO:0005737\"}},\"edges\":{}}}}"`
