### ISSUE TITLE
subclass_of working one way but not another?

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#96]
```
message = {
  "message": {
    "query_graph": {
      "nodes": {
        "n00": {
          "id": "MONDO:0100070",
          "category": "biolink:Disease"
        },
        "n01": {
          "category": "biolink:Disease"
        }
      },
      "edges": {
        "e00": {
          "subject": "n01",
          "object": "n00",
          "predicate":"biolink:subclass_of"
        }
      }
    }
  }
}
```

Can't find a query plan.   If I reverse the direction of the edge, I get results.  There are two places where I should be able to get subclass edges: the ontology KP or one of the automat platers (ontology something... don't remember the exact name)

**Comment by alongreyber** [comment]
After #119, this does return results from [https://automat.renci.org/ontological-hierarchy/reasonerapi](https://automat.renci.org/ontological-hierarchy/reasonerapi). If there's another source that we should be pulling from, feel free to reopen this issue.
