### ISSUE TITLE
Possible Service Outage

### ISSUE THREAD

**Issue by MarkDWilliams** [ranking-agent/strider#99]
Recently, Aragorn as it is registered in the ARS has been returning an error for all queries run through the ARS including ones which worked previously.  Has the URL changed or is there some other issue causing this?
Example message being received by the ARS
https://ars.transltr.io/ars/api/messages/8f309487-3e41-4d1a-b8ec-e676b8a78683
Query:
```json
{
  "message": {
    "query_graph": {
      "nodes": {
        "n00": {
          "id": "MONDO:0005784",
          "category": "biolink:Disease"
        },
        "n01": {
          "category": "biolink:Disease"
        }
      },
      "edges": {
        "e00": {
          "subject": "n00",
          "object": "n01",
          "predicate":"biolink:subclass_of"
        }
      }
    }
  }
}
```

**Comment by patrickkwang** [comment]
Thanks for the heads-up! We've been having outages as a result of a redis misconfiguration that is now hopefully resolved.

On a separate but related note, we actually have a newer, more robust deployment at strider.renci.org/docs. I will attempt to update the ARS registration.

**Comment by MarkDWilliams** [comment]
Sounds good, we've been having our own issues with registrations in the ARS.  So, let me know if you have any trouble there.
